language: node_js # 设置语言
node_js: stable # 设置相应版本
install:
    - npm install # 安装hexo及插件
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - cd ./public
    - git init
    - git config user.name "alien.he" # 修改name
    - git config user.email "753458929@qq.com" # 修改email
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${Travis-CI-TOKEN}@${GH_REF}" master:gh-pages # Travis-CI-TOKEN是在Travis中配置token的名称
branches:
    only:
        - gh-pages #只检测静态页面分支
env:
    global:
        - GH_REF: git@github.com:AlienwareHe/Alienware.github.io.git